### ISSUE TITLE
.cache file 不存在报错

### ISSUE THREAD

**Issue by peng051410** [yqrashawn/.emacs.d#1]
在启动时遇到错误：
`File is missing: Cannot open load file, No such file or directory, /Users/tomyli/.emacs.d/.cache/.custom-settings`

这个要怎么处理？

**Comment by yqrashawn** [comment]
可以试一下 `mkdir -p /Users/tomyli/.emacs.d/.cache/ && touch /Users/tomyli/.emacs.d/.cache/.custom-settings`
